### ISSUE TITLE
[Syphon]: Class JavaLaunchHelper is implemented in both 

### ISSUE THREAD

**Issue by Edwardffigueroa** [Syphon/Processing#30]
I can not use syphon in my intellij, could anyone help me? I have this problem:

objc[1344]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/bin/java and /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
java.lang.ClassCastException: processing.awt.PGraphicsJava2D cannot be cast to processing.opengl.PGraphicsOpenGL
	at codeanticode.syphon.SyphonServer.<init>(Unknown Source)
	at Main.setup(Main.java:27)
	at processing.core.PApplet.handleDraw(PApplet.java:2393)
	at processing.awt.PSurfaceAWT$12.callDraw(PSurfaceAWT.java:1540)
	at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:316)

**Comment by vade** [comment]
Holy shit dude please only post once.

-java.library.path=/Users/doekewartena/Dropbox/Public/Processing/libraries/Syphon/library

with your own path, no?
