### ISSUE TITLE
Apple silicone compatibility

### ISSUE THREAD

**Issue by orsjb** [Syphon/Processing#45]
From a fresh install of Processing 4 on an Apple M1, followed by installing the Syphon library via Processing, I get the following error in any Syphon example sketch:

UnsatisfiedLinkError: /Users/iml/Documents/Processing/libraries/Syphon/library/libJSyphon.jnilib: dlopen(/Users/iml/Documents/Processing/libraries/Syphon/library/libJSyphon.jnilib, 0x0001): tried: '/Users/iml/Documents/Processing/libraries/Syphon/library/libJSyphon.jnilib' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))
java.lang.UnsatisfiedLinkError: /Users/iml/Documents/Processing/libraries/Syphon/library/libJSyphon.jnilib: dlopen(/Users/iml/Documents/Processing/libraries/Syphon/library/libJSyphon.jnilib, 0x0001): tried: '/Users/iml/Documents/Processing/libraries/Syphon/library/libJSyphon.jnilib' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))
	at processing.opengl.PSurfaceJOGL.lambda$initAnimator$2(PSurfaceJOGL.java:426)
	at java.base/java.lang.Thread.run(Thread.java:833)
A library used by this sketch relies on native code that is not available.
UnsatisfiedLinkError: /Users/iml/Documents/Processing/libraries/Syphon/library/libJSyphon.jnilib: dlopen(/Users/iml/Documents/Processing/libraries/Syphon/library/libJSyphon.jnilib, 0x0001): tried: '/Users/iml/Documents/Processing/libraries/Syphon/library/libJSyphon.jnilib' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))
UnsatisfiedLinkError: /Users/iml/Documents/Processing/libraries/Syphon/library/libJSyphon.jnilib: dlopen(/Users/iml/Documents/Processing/libraries/Syphon/library/libJSyphon.jnilib, 0x0001): tried: '/Users/iml/Documents/Processing/libraries/Syphon/library/libJSyphon.jnilib' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))

Strangely, on a different Mac with M1 chip, it works.

**Comment by vade** [comment]
It likely works because processing is an Intel build running Rosetta. See the convo happening here: 

https://github.com/Syphon/Java/issues/7

**Comment by samyk** [comment]
Switch to the x86-64 Processing, I'm guessing the library will work out of the box in that case

**Comment by orsjb** [comment]
Ohhh I seeeeee. Sorry I misunderstood that when Vade first suggested it.
Done. And it works. Thank you so much.
